POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Liisa Marttinen",
    "number": "040-234563"
}

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/61a492fb055979ce0a9ddf74

###
DELETE http://localhost:3001/api/persons/2

###

